"""
Writes file_version_info.txt from version.py.
Called by build.bat before PyInstaller runs.
"""
from version import __version__, VERSION_TUPLE

t = VERSION_TUPLE
v = __version__

content = f"""# UTF-8
# Windows file version resource for Cadence.exe  —  auto-generated by generate_version_info.py

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={t},
    prodvers={t},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName',      'Cadence'),
          StringStruct('FileDescription',  'Cadence \u2014 Your consulting rhythm'),
          StringStruct('FileVersion',      '{v}'),
          StringStruct('InternalName',     'Cadence'),
          StringStruct('LegalCopyright',   ''),
          StringStruct('OriginalFilename', 'Cadence.exe'),
          StringStruct('ProductName',      'Cadence'),
          StringStruct('ProductVersion',   '{v}'),
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [0x0409, 0x04B0])])
  ]
)
"""

out = 'file_version_info.txt'
with open(out, 'w', encoding='utf-8') as f:
    f.write(content)
print(f'[OK] {out} written for version {v}')
